/*Modified code initially generated by GPT
https://chatgpt.com/share/35bfdeb0-151c-4111-bc8e-cfac26358a07 - first prompt
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include "constants.h"
#include "hop.h"


char *read_input();

char** tokenise_input(char* X);
int execute_command(char** tokens, char* homedir, char** prevdir, char* input);




