/*Modified code initially generated by GPT
https://chatgpt.com/share/35bfdeb0-151c-4111-bc8e-cfac26358a07 - first prompt
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include "constants.h"
#include "hop.h"
#include "pwd.h"
#include "reveal.h"


char *read_input(){
    char *input = malloc(MAX * sizeof(char));
    if(!input){
        fprintf(stderr, "allocation error\n");
        exit(EXIT_FAILURE);
    }

    if(fgets(input, MAX, stdin) == NULL){
        if(feof(stdin)){
            exit(EXIT_SUCCESS);  // EOF, exit shell
        }
        else{
            perror("read_input");
            exit(EXIT_FAILURE);
        }
    }

    return input;
}

char** tokenise_input(char* X){
    char* token;
    char** tokens = (char**)malloc(MAX*sizeof(char*));
    token=strtok(X, TOKEN_DELIMITERS);
    int count=0;
    while(token != NULL){
        tokens[count] = token;

        count++;
        //printf("%dth loop\n",count++);
        //printf("%s\n",token);
        token=strtok(NULL, TOKEN_DELIMITERS);
    }
    tokens[count] = NULL;
    return tokens;
}
int execute_command(char** tokens, char* homedir, char** ptrprevdir){
    if(strcmp(tokens[0],"hop")==0){
        char cwd[MAX];
        getcwd(cwd, MAX);
        if(hop(tokens, homedir, *ptrprevdir) == 0){
            if(strcmp(*ptrprevdir,"NULL")==0){
                *ptrprevdir = (char*)malloc(MAX*sizeof(char));
            }
            strcpy(*ptrprevdir, cwd);
        }
        //printf("prevdir is %s\n",*ptrprevdir);
    }else if(strcmp(tokens[0], "pwd")==0){
        pwd();
        printf("\n"); // goto nextline
    }else if(strcmp(tokens[0], "reveal")==0){
        reveal(tokens, homedir, *ptrprevdir);
    }
    else{
        fprintf(stderr, ""RED"INVALID COMMAND %s\n"RESET"",tokens[0]);
        return 1;
    }
    return 0;
}







