//input.h

/*Modified code initially generated by GPT
https://chatgpt.com/share/35bfdeb0-151c-4111-bc8e-cfac26358a07 - first prompt
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include "constants.h"
#include "hop.h"

//#ifdef Alias
#include "alias.h"




char *read_input();

char** tokenise_input(char* X);
int RUN_command(char** tokens, char* homedir, char** ptrprevdir, char* input, AliasList* aliases, int expand_alias_flag, pid_t shell_pid);
int execute_command(char** tokens, char* homedir, char** prevdir, char* input, AliasList* aliases, int expand_alias_flag, pid_t shell_pid);

//#endif





